### ISSUE TITLE
Pol2Reg.exe gets flagged as malicios by Chrome and Windows Defender

### ISSUE THREAD

**Issue by juergen-kc** [CCOSTAN/BlogPostStorage#7]
https://github.com/CCOSTAN/BlogPostStorage/blob/master/Pol2Reg.zip

**Comment by CCOSTAN** [comment]
Yes.  this is because it is written with AutoHotKey. 

Hey @JBensimon99 , Can we Update the package to just include the AutoHotkey Script source?

**Comment by JacqBens** [comment]
It's actually because the executable is compressed, in fact to protect the source code. I'm not keen to publish source, but I'd be willing to provide an uncompressed version -- if people figure out the source from that, so be it.
